@echo off
echo Starting Chemical Equipment Visualizer Web Frontend...
cd frontend
if not exist node_modules (
    echo Installing dependencies...
    npm install
)
echo Starting React development server...
npm start
