@echo off
echo Starting Chemical Equipment Visualizer Backend...
cd backend
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Running migrations...
python manage.py makemigrations
python manage.py migrate
echo Starting Django server...
python manage.py runserver
