@echo off
echo Starting Chemical Equipment Visualizer Desktop App...
cd desktop
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting desktop application...
python main.py
